# Authors {-}

## Ekarin E. Pongpipat, M.A. {-}

<a href="https://ekarinpongpipat.com/" target="_blank">Ekarin E. Pongpipat</a> is a Ph.D. student studying cognition and neuroscience at The University of Texas at Dallas. He obtained his undergraduate degree in psychology at California State University, Northridge and his master's degree in psychology at San Diego State University. Ekarin has over 5 years of teaching and tutoring experience within statistics. He is also interested in understanding how neural systems change with age.

## Giuseppe G. Miranda, M.S. {-}

<a href="https://giuseppegmiranda.com/" target="_blank">Giuseppe G. Miranda</a> is a Ph.D. student studying cognition and neuroscience at The University of Texas at Dallas. He obtained his undergraduate degree in psychology at the University of Dayton and his master's degree in applied cognition and neuroscience at The University of Texas at Dallas. He is interested in brain structure, aging, dopamine, and executive function, and also has interests in intervention research on increasing health span via direct methods such as exercise. He also has strong interests in data analysis and statistics. In his free time he enjoys playing basketball, exercising, traveling, and painting.

## Matthew J. Kmiecik, Ph.D {-}

<a href="https://mattkmiecik.com/" target="_blank">Matthew J. Kmiecik</a> is a postdoctoral research fellow at NorthShore University HealthSystem (Evanston Hospital, IL) studying the neural mechanisms underlying multimodal hypersensitivity in chronic pain conditions. He earned his PhD in Cognition and Neuroscience from The University of Texas at Dallas and his BS in Psychology: Natural Sciences from Loyola University Chicago. In his spare time Matt enjoys reading and playing sports.
