`r if (knitr::is_html_output()) '
# References {-}
'`

R Core Team. 2019 R: A Language and Environment for Statistical Computing. Vienna, Austria: 
  R Foundation for Statistical Computing. https://www.R-project.org/.

Hadley Wickham (2017). tidyverse: Easily Install and Load the 'Tidyverse'. R package version
  1.2.1. https://CRAN.R-project.org/package=tidyverse
  
Hadley Wickham (2018). scales: Scale Functions for Visualization. R package version 1.0.0.
  https://CRAN.R-project.org/package=scales
  
John Fox and Sanford Weisberg (2011). An {R} Companion to Applied Regression, Second Edition.
  Thousand Oaks CA: Sage. URL: http://socserv.socsci.mcmaster.ca/jfox/Books/Companion
  
John Fox, Sanford Weisberg and Brad Price (2018). carData: Companion to Applied Regression Data
  Sets. R package version 3.0-2. https://CRAN.R-project.org/package=carData

Revelle, W. (2018) psych: Procedures for Personality and Psychological Research, Northwestern
  University, Evanston, Illinois, USA, https://CRAN.R-project.org/package=psych Version = 1.8.12.

Venables, W. N. & Ripley, B. D. (2002). Modern Applied Statistics with S. Fourth Edition.
  Springer, New York. ISBN 0-387-95457-0
  
Yihui Xie (2014). knitr: A Comprehensive Tool for Reproducible Research in R. In Victoria Stodden,
  Friedrich Leisch and Roger D. Peng, editors, Implementing Reproducible Computational Research.
  Chapman and Hall/CRC. ISBN 978-1466561595
  
Yihui Xie (2015). Dynamic Documents with R and knitr. 2nd edition. Chapman and Hall/CRC. ISBN
  978-1498716963

Yihui Xie (2016). bookdown: Authoring Books and Technical Documents with R Markdown. Chapman and
  Hall/CRC. ISBN 978-1138700109
  
Yihui Xie (2018). bookdown: Authoring Books and Technical Documents with R Markdown. R package
  version 0.9.
  
Yihui Xie (2018). knitr: A General-Purpose Package for Dynamic Report Generation in R. R package
  version 1.21.

