<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Chapter 5 Simple Linear Regression | A Practical Extension of Introductory Statistics in Psychology using R (Draft)</title>
  <meta name="description" content="This book aims to provide a practical extension of introductory statistics typically taught in psychology into the general linear model (GLM) using R.">
  <meta name="generator" content="bookdown  and GitBook 2.6.7">

  <meta property="og:title" content="Chapter 5 Simple Linear Regression | A Practical Extension of Introductory Statistics in Psychology using R (Draft)" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="https://ekarinpongpipat.com/practical-ext-of-intro-stats-in-psy-using-R/" />
  
  <meta property="og:description" content="This book aims to provide a practical extension of introductory statistics typically taught in psychology into the general linear model (GLM) using R." />
  <meta name="github-repo" content="epongpipat/practical-ext-of-intro-stats-in-psy-using-R" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 5 Simple Linear Regression | A Practical Extension of Introductory Statistics in Psychology using R (Draft)" />
  
  <meta name="twitter:description" content="This book aims to provide a practical extension of introductory statistics typically taught in psychology into the general linear model (GLM) using R." />
  

<meta name="author" content="Ekarin Eric Pongpipat, M.A. &amp; Giuseppe Miranda, M.S.">



  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="datasets.html">
<link rel="next" href="correlation.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; background-color: #f8f8f8; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
pre, code { background-color: #f8f8f8; }
code > span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code > span.dt { color: #204a87; } /* DataType */
code > span.dv { color: #0000cf; } /* DecVal */
code > span.bn { color: #0000cf; } /* BaseN */
code > span.fl { color: #0000cf; } /* Float */
code > span.ch { color: #4e9a06; } /* Char */
code > span.st { color: #4e9a06; } /* String */
code > span.co { color: #8f5902; font-style: italic; } /* Comment */
code > span.ot { color: #8f5902; } /* Other */
code > span.al { color: #ef2929; } /* Alert */
code > span.fu { color: #000000; } /* Function */
code > span.er { color: #a40000; font-weight: bold; } /* Error */
code > span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #000000; } /* Constant */
code > span.sc { color: #000000; } /* SpecialChar */
code > span.vs { color: #4e9a06; } /* VerbatimString */
code > span.ss { color: #4e9a06; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #000000; } /* Variable */
code > span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code > span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code > span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code > span.ex { } /* Extension */
code > span.at { color: #c4a000; } /* Attribute */
code > span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code > span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Table of Contents</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a><ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#what-exactly-is-the-glm"><i class="fa fa-check"></i><b>1.1</b> What exactly is the GLM?</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#how-will-this-book-be-covered"><i class="fa fa-check"></i><b>1.2</b> How will this book be covered?</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#what-wont-this-book-cover"><i class="fa fa-check"></i><b>1.3</b> What won’t this book cover?</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#why-r"><i class="fa fa-check"></i><b>1.4</b> Why R?</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="prerequisites.html"><a href="prerequisites.html"><i class="fa fa-check"></i><b>2</b> Prerequisites</a><ul>
<li class="chapter" data-level="2.1" data-path="prerequisites.html"><a href="prerequisites.html#knowledge"><i class="fa fa-check"></i><b>2.1</b> Knowledge</a></li>
<li class="chapter" data-level="2.2" data-path="prerequisites.html"><a href="prerequisites.html#software"><i class="fa fa-check"></i><b>2.2</b> Software</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="r-packages.html"><a href="r-packages.html"><i class="fa fa-check"></i><b>3</b> R Packages</a><ul>
<li class="chapter" data-level="3.1" data-path="r-packages.html"><a href="r-packages.html#what-are-packages"><i class="fa fa-check"></i><b>3.1</b> What are packages?</a></li>
<li class="chapter" data-level="3.2" data-path="r-packages.html"><a href="r-packages.html#packages"><i class="fa fa-check"></i><b>3.2</b> Packages</a></li>
<li class="chapter" data-level="3.3" data-path="r-packages.html"><a href="r-packages.html#install-r-packages"><i class="fa fa-check"></i><b>3.3</b> Install R Packages</a></li>
<li class="chapter" data-level="3.4" data-path="r-packages.html"><a href="r-packages.html#load-r-packages"><i class="fa fa-check"></i><b>3.4</b> Load R Packages</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="datasets.html"><a href="datasets.html"><i class="fa fa-check"></i><b>4</b> Datasets</a><ul>
<li class="chapter" data-level="4.1" data-path="datasets.html"><a href="datasets.html#salaries-dataset"><i class="fa fa-check"></i><b>4.1</b> Salaries Dataset</a><ul>
<li class="chapter" data-level="4.1.1" data-path="datasets.html"><a href="datasets.html#data-wrangling"><i class="fa fa-check"></i><b>4.1.1</b> Data Wrangling</a></li>
<li class="chapter" data-level="4.1.2" data-path="datasets.html"><a href="datasets.html#descriptive-statistics"><i class="fa fa-check"></i><b>4.1.2</b> Descriptive Statistics</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="datasets.html"><a href="datasets.html#anorexia-dataset"><i class="fa fa-check"></i><b>4.2</b> Anorexia Dataset</a><ul>
<li class="chapter" data-level="4.2.1" data-path="datasets.html"><a href="datasets.html#data-wrangling-1"><i class="fa fa-check"></i><b>4.2.1</b> Data Wrangling</a></li>
<li class="chapter" data-level="4.2.2" data-path="datasets.html"><a href="datasets.html#descriptive-statistics-1"><i class="fa fa-check"></i><b>4.2.2</b> Descriptive Statistics</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="datasets.html"><a href="datasets.html#use-your-own-dataset"><i class="fa fa-check"></i><b>4.3</b> Use Your Own Dataset</a></li>
</ul></li>
<li class="part"><span><b>I Introductory Univariate Statistics</b></span></li>
<li class="chapter" data-level="5" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html"><i class="fa fa-check"></i><b>5</b> Simple Linear Regression</a><ul>
<li class="chapter" data-level="5.1" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#null-and-research-hypotheses"><i class="fa fa-check"></i><b>5.1</b> Null and research hypotheses</a></li>
<li class="chapter" data-level="5.2" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#statistical-analyses"><i class="fa fa-check"></i><b>5.2</b> Statistical analyses</a><ul>
<li class="chapter" data-level="5.2.1" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#how-do-we-read-the-anova-source-table"><i class="fa fa-check"></i><b>5.2.1</b> How do we read the ANOVA source table?</a></li>
<li class="chapter" data-level="5.2.2" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#how-do-we-read-the-coefficients-table"><i class="fa fa-check"></i><b>5.2.2</b> How do we read the coefficients table?</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#statistical-decision"><i class="fa fa-check"></i><b>5.3</b> Statistical decision</a></li>
<li class="chapter" data-level="5.4" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#apa-statement"><i class="fa fa-check"></i><b>5.4</b> APA statement</a></li>
<li class="chapter" data-level="5.5" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#visualization"><i class="fa fa-check"></i><b>5.5</b> Visualization</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="correlation.html"><a href="correlation.html"><i class="fa fa-check"></i><b>6</b> Correlation</a><ul>
<li class="chapter" data-level="6.1" data-path="correlation.html"><a href="correlation.html#null-and-research-hypotheses-1"><i class="fa fa-check"></i><b>6.1</b> Null and research hypotheses</a><ul>
<li class="chapter" data-level="6.1.1" data-path="correlation.html"><a href="correlation.html#traditional-approach"><i class="fa fa-check"></i><b>6.1.1</b> Traditional approach</a></li>
<li class="chapter" data-level="6.1.2" data-path="correlation.html"><a href="correlation.html#glm-approach"><i class="fa fa-check"></i><b>6.1.2</b> GLM approach</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="correlation.html"><a href="correlation.html#statistical-analysis"><i class="fa fa-check"></i><b>6.2</b> Statistical analysis</a><ul>
<li class="chapter" data-level="6.2.1" data-path="correlation.html"><a href="correlation.html#traditional-approach-1"><i class="fa fa-check"></i><b>6.2.1</b> Traditional approach</a></li>
<li class="chapter" data-level="6.2.2" data-path="correlation.html"><a href="correlation.html#glm-approach-1"><i class="fa fa-check"></i><b>6.2.2</b> GLM approach</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="correlation.html"><a href="correlation.html#statistical-decision-1"><i class="fa fa-check"></i><b>6.3</b> Statistical decision</a></li>
<li class="chapter" data-level="6.4" data-path="correlation.html"><a href="correlation.html#apa-statement-1"><i class="fa fa-check"></i><b>6.4</b> APA statement</a></li>
<li class="chapter" data-level="6.5" data-path="correlation.html"><a href="correlation.html#visualization-1"><i class="fa fa-check"></i><b>6.5</b> Visualization</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="one-sample-t-test.html"><a href="one-sample-t-test.html"><i class="fa fa-check"></i><b>7</b> One Sample <em>t</em>-Test</a><ul>
<li class="chapter" data-level="7.1" data-path="one-sample-t-test.html"><a href="one-sample-t-test.html#null-and-research-hypotheses-2"><i class="fa fa-check"></i><b>7.1</b> Null and research hypotheses</a><ul>
<li class="chapter" data-level="7.1.1" data-path="one-sample-t-test.html"><a href="one-sample-t-test.html#traditional-approach-2"><i class="fa fa-check"></i><b>7.1.1</b> Traditional Approach</a></li>
<li class="chapter" data-level="7.1.2" data-path="one-sample-t-test.html"><a href="one-sample-t-test.html#glm-approach-2"><i class="fa fa-check"></i><b>7.1.2</b> GLM Approach</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="one-sample-t-test.html"><a href="one-sample-t-test.html#statistical-analysis-1"><i class="fa fa-check"></i><b>7.2</b> Statistical analysis</a><ul>
<li class="chapter" data-level="7.2.1" data-path="one-sample-t-test.html"><a href="one-sample-t-test.html#traditional-approach-3"><i class="fa fa-check"></i><b>7.2.1</b> Traditional Approach</a></li>
<li class="chapter" data-level="7.2.2" data-path="one-sample-t-test.html"><a href="one-sample-t-test.html#glm-approach-3"><i class="fa fa-check"></i><b>7.2.2</b> GLM Approach</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="one-sample-t-test.html"><a href="one-sample-t-test.html#statistical-decision-2"><i class="fa fa-check"></i><b>7.3</b> Statistical decision</a></li>
<li class="chapter" data-level="7.4" data-path="one-sample-t-test.html"><a href="one-sample-t-test.html#apa-statement-2"><i class="fa fa-check"></i><b>7.4</b> APA statement</a></li>
<li class="chapter" data-level="7.5" data-path="one-sample-t-test.html"><a href="one-sample-t-test.html#visualization-2"><i class="fa fa-check"></i><b>7.5</b> Visualization</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="dependent-samples-t-test.html"><a href="dependent-samples-t-test.html"><i class="fa fa-check"></i><b>8</b> Dependent Samples <em>t</em>-Test</a><ul>
<li class="chapter" data-level="8.1" data-path="dependent-samples-t-test.html"><a href="dependent-samples-t-test.html#null-and-research-hypotheses-3"><i class="fa fa-check"></i><b>8.1</b> Null and research hypotheses</a><ul>
<li class="chapter" data-level="8.1.1" data-path="dependent-samples-t-test.html"><a href="dependent-samples-t-test.html#traditional-approach-4"><i class="fa fa-check"></i><b>8.1.1</b> Traditional approach</a></li>
<li class="chapter" data-level="8.1.2" data-path="dependent-samples-t-test.html"><a href="dependent-samples-t-test.html#glm-approach-4"><i class="fa fa-check"></i><b>8.1.2</b> GLM approach</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="dependent-samples-t-test.html"><a href="dependent-samples-t-test.html#statistical-analysis-2"><i class="fa fa-check"></i><b>8.2</b> Statistical analysis</a><ul>
<li class="chapter" data-level="8.2.1" data-path="dependent-samples-t-test.html"><a href="dependent-samples-t-test.html#traditional-approach-5"><i class="fa fa-check"></i><b>8.2.1</b> Traditional approach</a></li>
<li class="chapter" data-level="8.2.2" data-path="dependent-samples-t-test.html"><a href="dependent-samples-t-test.html#glm-approach-5"><i class="fa fa-check"></i><b>8.2.2</b> GLM approach</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="dependent-samples-t-test.html"><a href="dependent-samples-t-test.html#statistical-decision-3"><i class="fa fa-check"></i><b>8.3</b> Statistical decision</a></li>
<li class="chapter" data-level="8.4" data-path="dependent-samples-t-test.html"><a href="dependent-samples-t-test.html#apa-statement-3"><i class="fa fa-check"></i><b>8.4</b> APA statement</a></li>
<li class="chapter" data-level="8.5" data-path="dependent-samples-t-test.html"><a href="dependent-samples-t-test.html#visualization-3"><i class="fa fa-check"></i><b>8.5</b> Visualization</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="independent-samples-t-test.html"><a href="independent-samples-t-test.html"><i class="fa fa-check"></i><b>9</b> Independent Samples <em>t</em>-Test</a><ul>
<li class="chapter" data-level="9.1" data-path="independent-samples-t-test.html"><a href="independent-samples-t-test.html#null-and-research-hypotheses-4"><i class="fa fa-check"></i><b>9.1</b> Null and research hypotheses</a><ul>
<li class="chapter" data-level="9.1.1" data-path="independent-samples-t-test.html"><a href="independent-samples-t-test.html#traditional-approach-6"><i class="fa fa-check"></i><b>9.1.1</b> Traditional approach</a></li>
<li class="chapter" data-level="9.1.2" data-path="independent-samples-t-test.html"><a href="independent-samples-t-test.html#glm-approach-6"><i class="fa fa-check"></i><b>9.1.2</b> GLM approach</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="independent-samples-t-test.html"><a href="independent-samples-t-test.html#statistical-analysis-3"><i class="fa fa-check"></i><b>9.2</b> Statistical analysis</a><ul>
<li class="chapter" data-level="9.2.1" data-path="independent-samples-t-test.html"><a href="independent-samples-t-test.html#traditional-approach-7"><i class="fa fa-check"></i><b>9.2.1</b> Traditional approach</a></li>
<li class="chapter" data-level="9.2.2" data-path="independent-samples-t-test.html"><a href="independent-samples-t-test.html#glm-approach-7"><i class="fa fa-check"></i><b>9.2.2</b> GLM approach</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="independent-samples-t-test.html"><a href="independent-samples-t-test.html#statistical-decision-4"><i class="fa fa-check"></i><b>9.3</b> Statistical decision</a></li>
<li class="chapter" data-level="9.4" data-path="independent-samples-t-test.html"><a href="independent-samples-t-test.html#apa-statement-4"><i class="fa fa-check"></i><b>9.4</b> APA statement</a></li>
<li class="chapter" data-level="9.5" data-path="independent-samples-t-test.html"><a href="independent-samples-t-test.html#visualization-4"><i class="fa fa-check"></i><b>9.5</b> Visualization</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="one-way-anova.html"><a href="one-way-anova.html"><i class="fa fa-check"></i><b>10</b> One-Way ANOVA</a><ul>
<li class="chapter" data-level="10.1" data-path="one-way-anova.html"><a href="one-way-anova.html#coding-categorical-variables"><i class="fa fa-check"></i><b>10.1</b> Coding Categorical Variables</a><ul>
<li class="chapter" data-level="10.1.1" data-path="one-way-anova.html"><a href="one-way-anova.html#dummy-coding"><i class="fa fa-check"></i><b>10.1.1</b> Dummy Coding</a></li>
<li class="chapter" data-level="10.1.2" data-path="one-way-anova.html"><a href="one-way-anova.html#othogon"><i class="fa fa-check"></i><b>10.1.2</b> Orthogonal Coding</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="one-way-anova.html"><a href="one-way-anova.html#null-and-research-hypothesis"><i class="fa fa-check"></i><b>10.2</b> Null and research hypothesis</a><ul>
<li class="chapter" data-level="10.2.1" data-path="one-way-anova.html"><a href="one-way-anova.html#traditional-approach-8"><i class="fa fa-check"></i><b>10.2.1</b> Traditional approach</a></li>
<li class="chapter" data-level="10.2.2" data-path="one-way-anova.html"><a href="one-way-anova.html#glm-approach-8"><i class="fa fa-check"></i><b>10.2.2</b> GLM approach</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="one-way-anova.html"><a href="one-way-anova.html#statistical-analysis-4"><i class="fa fa-check"></i><b>10.3</b> Statistical analysis</a><ul>
<li class="chapter" data-level="10.3.1" data-path="one-way-anova.html"><a href="one-way-anova.html#traditional-approach-9"><i class="fa fa-check"></i><b>10.3.1</b> Traditional approach</a></li>
<li class="chapter" data-level="10.3.2" data-path="one-way-anova.html"><a href="one-way-anova.html#glm-approach-9"><i class="fa fa-check"></i><b>10.3.2</b> GLM approach</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="one-way-anova.html"><a href="one-way-anova.html#statistical-decision-5"><i class="fa fa-check"></i><b>10.4</b> Statistical decision</a></li>
<li class="chapter" data-level="10.5" data-path="one-way-anova.html"><a href="one-way-anova.html#apa-statement-5"><i class="fa fa-check"></i><b>10.5</b> APA statement</a></li>
<li class="chapter" data-level="10.6" data-path="one-way-anova.html"><a href="one-way-anova.html#visualization-5"><i class="fa fa-check"></i><b>10.6</b> Visualization</a><ul>
<li class="chapter" data-level="10.6.1" data-path="one-way-anova.html"><a href="one-way-anova.html#traditional"><i class="fa fa-check"></i><b>10.6.1</b> Traditional</a></li>
<li class="chapter" data-level="10.6.2" data-path="one-way-anova.html"><a href="one-way-anova.html#orthogonal-contrast-coding"><i class="fa fa-check"></i><b>10.6.2</b> Orthogonal Contrast Coding</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="factorial-anova.html"><a href="factorial-anova.html"><i class="fa fa-check"></i><b>11</b> Factorial ANOVA</a><ul>
<li class="chapter" data-level="11.1" data-path="factorial-anova.html"><a href="factorial-anova.html#null-and-research-hypotheses-5"><i class="fa fa-check"></i><b>11.1</b> Null and research hypotheses</a><ul>
<li class="chapter" data-level="11.1.1" data-path="factorial-anova.html"><a href="factorial-anova.html#traditional-approach-10"><i class="fa fa-check"></i><b>11.1.1</b> Traditional Approach</a></li>
<li class="chapter" data-level="11.1.2" data-path="factorial-anova.html"><a href="factorial-anova.html#glm-approach-10"><i class="fa fa-check"></i><b>11.1.2</b> GLM Approach</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="factorial-anova.html"><a href="factorial-anova.html#statistical-analysis-5"><i class="fa fa-check"></i><b>11.2</b> Statistical analysis</a><ul>
<li class="chapter" data-level="11.2.1" data-path="factorial-anova.html"><a href="factorial-anova.html#traditional-approach-11"><i class="fa fa-check"></i><b>11.2.1</b> Traditional approach</a></li>
<li class="chapter" data-level="11.2.2" data-path="factorial-anova.html"><a href="factorial-anova.html#glm-approach-11"><i class="fa fa-check"></i><b>11.2.2</b> GLM approach</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="factorial-anova.html"><a href="factorial-anova.html#statistical-decision-6"><i class="fa fa-check"></i><b>11.3</b> Statistical decision</a></li>
<li class="chapter" data-level="11.4" data-path="factorial-anova.html"><a href="factorial-anova.html#apa-statement-6"><i class="fa fa-check"></i><b>11.4</b> APA statement</a></li>
<li class="chapter" data-level="11.5" data-path="factorial-anova.html"><a href="factorial-anova.html#visualization-6"><i class="fa fa-check"></i><b>11.5</b> Visualization</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="glm-approach-summary.html"><a href="glm-approach-summary.html"><i class="fa fa-check"></i><b>12</b> GLM Approach Summary</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="chapter" data-level="" data-path="acknowledgements.html"><a href="acknowledgements.html"><i class="fa fa-check"></i>Acknowledgements</a></li>
<li class="chapter" data-level="" data-path="authors.html"><a href="authors.html"><i class="fa fa-check"></i>Authors</a><ul>
<li class="chapter" data-level="" data-path="authors.html"><a href="authors.html#ekarin-eric-pongpipat-m.a."><i class="fa fa-check"></i>Ekarin Eric Pongpipat, M.A.</a></li>
<li class="chapter" data-level="" data-path="authors.html"><a href="authors.html#giuseppe-miranda-m.s."><i class="fa fa-check"></i>Giuseppe Miranda, M.S.</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">A Practical Extension of Introductory Statistics in Psychology using R (Draft)</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="simple_linear_regression" class="section level1">
<h1><span class="header-section-number">Chapter 5</span> Simple Linear Regression</h1>
<p>The first analysis that we will go over is the simple linear regression. Typically, this is one of the last analyses that is taught in introductory statistics in psychology; however, we will go over the simple linear regression first because its steps are essentially identical to the GLM (i.e., OLS regression) and provides a foundation for the GLM framework.</p>
<p>The simple linear regression is typically taught to be used in understanding the relationship between two continuous variables, especially if one can predict the other.</p>
<p>However, the simple linear regression is a specific case of regression<a href="#fn2" class="footnoteRef" id="fnref2"><sup>2</sup></a> where variables can actually be either continuous or categorical, the number of predictor variables can be more than one, and causation is not a requirement. Thus, regression is applicable to most data types.</p>
<p>The simple linear regression is written as:</p>
<p><span class="math display">\[Y = \beta_0 + \beta_1X + \varepsilon\]</span></p>
<p>where <span class="math inline">\(Y\)</span> is the dependent (or response) variable, <span class="math inline">\(\beta_0\)</span> is the intercept, <span class="math inline">\(\beta_1\)</span> is the slope, <span class="math inline">\(X\)</span> is the independent (or predictor) variable, and <span class="math inline">\(\varepsilon\)</span> is the error.</p>
<p>We will use the terms dependent variable (DV) and response variable interchangeably throughout the book. We will also use the terms independent variable (IV) or predictor variable interchangeably.</p>
<p><span class="math inline">\(\beta\)</span> represents the true population value, while <span class="math inline">\(b\)</span> represents the unstandardized estimate of the true population value that we will obtain from our analysis. For example, <span class="math inline">\(\beta_1\)</span> represents the true population slope, while <span class="math inline">\(b_1\)</span> represents the unstandardized estimate of the true population slope (or sample).</p>
<p>Thus, a predicted model (as opposed to the above true hypothesized model) would be written as:</p>
<p><span class="math display">\[\hat{Y} = b_0 + b_1X\]</span></p>
<p>where <span class="math inline">\(\hat{Y}\)</span> represents the predicted dependent (or response) variable.</p>
<p>Both equations should look familiar to the slope-intercept form learned in algebra:</p>
<p><span class="math display">\[y = mx + b\]</span></p>
<p>where <span class="math inline">\(b\)</span> is the intercept, and <span class="math inline">\(m\)</span> is the slope.</p>
<p>The intercept and slope have the <strong>same</strong> meaning as they did in algebra. The intercept represents the value of <span class="math inline">\(Y\)</span> when <span class="math inline">\(X\)</span> is 0, and the slope represents the change in <span class="math inline">\(Y\)</span> (<span class="math inline">\(\Delta Y\)</span>) over the change in <span class="math inline">\(X\)</span> (<span class="math inline">\(\Delta X\)</span>). In other words, the intercept represents the value of the DV when the IV is 0, and the slope represents the change in the DV over the change in the IV.</p>
<p>Note that the <span class="math inline">\(b\)</span> in the slope-intercept form is not the same and should not be confused with the <span class="math inline">\(b\)</span> in the simple linear regression. The <span class="math inline">\(b\)</span> in the simple linear regression is the slope, while the <span class="math inline">\(b\)</span> in the slope-intercept form is the intercept. Unfortunately, using the same symbol for different terms and using different symbols for the same term is prevalent in statistics.</p>
<p>For a practical example of the simple linear regression, let’s say that we were interested in examining if there is a relationship between the amount of years since a professor has earned their Ph.D. and their salary.</p>
<p>For this example, we will use the <a href="datasets.html#salaries-dataset"><code>datasetSalaries</code></a> dataset.</p>
<div id="null-and-research-hypotheses" class="section level2">
<h2><span class="header-section-number">5.1</span> Null and research hypotheses</h2>
<p><span class="math display">\[Model: Salary = \beta_0 + \beta_1 Years.Since.PhD + \varepsilon\]</span> <span class="math display">\[H_0: \beta_1 = 0\]</span> <span class="math display">\[H_1: \beta_1 \ne 0\]</span></p>
<p>where <span class="math inline">\(\beta_0\)</span> is the intercept, <span class="math inline">\(\beta_1\)</span> is the slope, <span class="math inline">\(H_0\)</span> is the null hypothesis and <span class="math inline">\(H_1\)</span> is the research or alternative hypothesis. Typically, the model is written as the hypothesized true model and thus the use of <span class="math inline">\(\beta\)</span> rather than <span class="math inline">\(b\)</span>.</p>
<p>In this example, the null hypothesis states that the slope is equal to 0, or that there is no relationship between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>. Specifically, in this example, there is no relationship between years since a professor has earned their Ph.D. and their 9-month academic salary. (Note: The null hypothesis is sometimes referred to as the nil hypothesis in psychology since we are typically comparing our estimate against 0, or nil).</p>
<p>The research hypothesis states that the slope is not equal to 0, or that there is a relationship between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>. Specifically, in this example, there is a relationship between years since a professor has earned their Ph.D. and their salary.</p>
<p>The model, null hypothesis, and research hypothesis are identical for both traditional and GLM approaches.</p>
<p>The intercept can also be tested and its null and research hypotheses are: <span class="math display">\[H_0: \beta_0 = 0\]</span> <span class="math display">\[H_1: \beta_0 \ne 0\]</span></p>
<p>The null hypothesis states that the intercept is equal to 0. In other words, the value of <span class="math inline">\(Y\)</span> when <span class="math inline">\(X\)</span> is 0 is not different than 0. Specifically, in this example, the salary of professors who have earned their Ph.D. for less than a year is essentially equal to $0. (Note: Zero represents professors who have just earned their Ph.D. up to those who have earned their Ph.D. for less than a year because <code>yrs.since.phd</code> was collected as integers and anything less than a year would be coded as 0.)</p>
<p>The research hypothesis states that the intercept is not equal to 0. In other words, the value of <span class="math inline">\(Y\)</span> when <span class="math inline">\(X\)</span> is 0 is different than 0. Specifically, in this example, the salary of professors who have earned their Ph.D. for less than a year is essentially different than (or not equal to) $0.</p>
<p>Again, the null and research hypotheses are identical for both traditional and GLM approaches.</p>
</div>
<div id="statistical-analyses" class="section level2">
<h2><span class="header-section-number">5.2</span> Statistical analyses</h2>
<p>To perform the simple linear regression in R, we can use the <code>lm</code> function.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">model &lt;-<span class="st"> </span><span class="kw">lm</span>(<span class="dt">formula =</span> salary <span class="op">~</span><span class="st"> </span>yrs.since.phd, <span class="dt">data =</span> datasetSalaries)</code></pre></div>
<p>The first input is the formula of the model, which is the DV, followed by a tilde sign (<code>~</code>), followed by the IV.</p>
<p>In our case, the DV of <code>salary</code> is be the first variable, followed by a <code>~</code> and the IV of <code>yrs.since.phd</code>. Notice the similarity between the model and formula. The second input is the dataset (i.e., <code>datasetSalaries</code>).</p>
<p>We will save the analysis into an object named <code>model</code>. <code>model</code> can be any name and was chosen for simplicity.</p>
<p><br></p>
<p>We can obtain the ANOVA source table by using the <code>Anova</code> function within the <code>cars</code> package.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">Anova</span>(model, <span class="dt">type =</span> <span class="dv">3</span>)</code></pre></div>
<pre><code>## Anova Table (Type III tests)
## 
## Response: salary
##                   Sum Sq  Df  F value    Pr(&gt;F)    
## (Intercept)   8.3369e+11   1 1099.706 &lt; 2.2e-16 ***
## yrs.since.phd 6.3852e+10   1   84.226 &lt; 2.2e-16 ***
## Residuals     2.9945e+11 395                       
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Note: We prefer the <code>Anova</code> function with a capitol <strong>A</strong> over the <code>anova</code> function with a lowercase <strong>a</strong> because we can specify the type of sum of squares. Breifly, The sum of squares in the <code>anova</code> function is type I sums of squares and cannot be changed while we can specify type III sums of squares using the <code>Anova</code> function. In short, type I sums of squares performs a sequential test while type III sums of squares performs a simultaneous test. In other words, type I sums of squares partials out shared infomation between the IVs sequentially, while type III sums of squares partials out information shared between each IV from each other simulataneously from the start. The results from using type I and type III sums of squares will be the same if there is only one IV. However, if there is more than one IV, only the last IV will be the same using either type I and type III sums of squares since all information from prior IVs will be partialled out.</p>
<div id="how-do-we-read-the-anova-source-table" class="section level3">
<h3><span class="header-section-number">5.2.1</span> How do we read the ANOVA source table?</h3>
<p>We can look at the variable of interest in the first column and read across that particular variable’s row for its statistical information.</p>
<p>For example, let’s first examine the statistics associated with the variable <code>(Intercept)</code>. The sums of squares (<code>Sum Sq</code>, which is also abbreviated as <span class="math inline">\(SS\)</span>) associated with the <code>(Intercept)</code> is <code>8.37e+11</code>, the degrees of freedom (<code>Df</code>, specifically, degrees of freedom reduced) is <code>1</code>, the <em>F</em>-statistic (<code>F value</code>) is 1099.71, and the p-value (<code>Pr&gt;F</code>) is <code>&lt; 2.2e-16</code>.</p>
<p>The <code>F value</code> or <em>F</em>-statistic conceptually provides a ratio of explained and unexplained variability to unexplained variability. Explained variability is how much the DV can be explained by IVs while unexplained variability is how much variability is not explained by the DV.</p>
<p>The mathematical formula of the <em>F</em>-statistic can conceptually be thought of as:</p>
<p><span class="math display">\[F = \frac{explained\ variability}{unexplained\ variability}\]</span></p>
<p>Thus, if the IV can’t explain any of the variability within the DV, then the <em>F</em>-statistic is less than or equal to 1.</p>
<p>However, if the IV(s) can explain the DV, the <em>F</em>-statistic will be larger than 1.</p>
<p>In other words, the higher the <em>F</em>-statistic, the more the IV(s) explain(s) the variability in the DV compared to its inability to explain the DV.</p>
<p>Thus, the interpretation of the <em>F</em>-statistic of the <code>(Intercept)</code> is that the <code>(Intercept)</code> can explain the variability in <code>salary</code> <code>1099.71</code> times more than the <code>(Intercept)</code>’s inability to explain the variability in salary. If interested in the mathematical formula and its calculation, see the footnote at the bottom of the page.<a href="#fn3" class="footnoteRef" id="fnref3"><sup>3</sup></a></p>
<p>The <code>Pr(&gt;F)</code> or <em>p</em>-value associated with the <code>Intercept</code> is <code>&lt; 2.2e-16</code>. The <em>p</em>-value is the probability of obtaining that particular <em>F</em>-statistic or more extreme assuming that the null hypothesis is true. In other words, the probability of obtaining this <em>F</em>-statistic by chance is extremely small.</p>
<p>Since <code>yrs.since.phd</code> was our main predictor of interest (and for extra practice), let’s also look at the statistics associated with <code>yrs.since.phd</code>.</p>
<p>The <em>F</em>-statistic associated with <code>yrs.since.phd</code> is <code>84.23</code>, and can be interpreted as <code>yrs.since.phd</code> explains the variability in <code>salary</code> <code>84.23</code> times more than <code>years.since.phd</code>’s inability to expain the variability in salary. The mathematical formula and calculation for <code>yrs.since.phd</code> can also be seen in the footnotes section.<a href="#fn4" class="footnoteRef" id="fnref4"><sup>4</sup></a></p>
<p>The <em>p</em>-value associated with <code>yrs.since.phd</code> is also <code>&lt; 2.2e-16</code> with identical interpretations for the <em>p</em>-value of the <code>(Intercept)</code>.</p>
<p><br></p>
<p>We can also obtain the coefficients table by using the <code>summary</code> function.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(model)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = salary ~ yrs.since.phd, data = datasetSalaries)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -84171 -19432  -2858  16086 102383 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)    91718.7     2765.8  33.162   &lt;2e-16 ***
## yrs.since.phd    985.3      107.4   9.177   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 27530 on 395 degrees of freedom
## Multiple R-squared:  0.1758, Adjusted R-squared:  0.1737 
## F-statistic: 84.23 on 1 and 395 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div id="how-do-we-read-the-coefficients-table" class="section level3">
<h3><span class="header-section-number">5.2.2</span> How do we read the coefficients table?</h3>
<p>Similarly, we can look at the variable of interest in the first column and read across that particular variable’s row for its statistical information.</p>
<p>Again, let’s first take a look at the statistics associated with the <code>(Intercept)</code>. The <code>Estimate</code> of the <code>(Intercept)</code> is <code>91718.7</code>, the standard error (<code>Std. Error</code>) is <code>2765.8</code>, the <em>t</em>-statistic (<code>t value</code>) is 33.162, and the <em>p</em>-value (<code>(Pr&gt;|t|)</code>) is <code>&lt; 2e-16</code>.</p>
<p>The <code>Estimate</code> of the <code>(Intercept)</code> is the predicted intercept value, <span class="math inline">\(b_0 = 91718.7\)</span>. Thus, the predicted <code>salary</code> when <span class="math inline">\(yrs.since.phd = 0\)</span> is $91,718.70. In other words, when a professor has had their Ph.D. for less than a year, their salary is predicted to be $91,718.70.</p>
<p>The <code>t value</code> or <em>t</em>-statistic is similar to the <em>F</em>-statistic, and can also be conceptually thought of as the ratio of systematic differences to unsystematic differences. The <em>t</em>-statistic is equal to the square root of the <em>F</em>-statistic when the degrees of freedom is 1,<a href="#fn5" class="footnoteRef" id="fnref5"><sup>5</sup></a>.<a href="#fn6" class="footnoteRef" id="fnref6"><sup>6</sup></a> Thus, the <em>t</em>-statistic interpretation is that the <code>(Intercept)</code> explains the variability in <code>salary</code> <code>33.162</code> times more than its inability to explain <code>salary</code>.</p>
<p>The <em>p</em>-value or <code>Pr(&gt;|t|)</code> of <code>&lt;2e-16</code> is the probability of obtaining that particular <em>t</em>-statistic or a value more extreme than the <em>t</em>-statistic assuming that the null hypothesis is true, which is the same value from the ANOVA source table.</p>
<p>Let’s also examine statistics for <code>yrs.since.phd</code>. The <code>Estimate</code> of <code>yrs.since.phd</code> is <code>985.3</code>, the <code>Std. Error</code> is <code>107.4</code>, the <code>t value</code> is <code>9.18</code>, and the <code>Pr(&gt;|t|)</code> is <code>&lt;2e-16</code>.</p>
<p>The <code>Estimate</code> of the <code>yrs.since.phd</code> is the estimated slope, <span class="math inline">\(b_1 = 985.3\)</span>. Thus, <code>salary</code> is predicted to change by <code>$985.30</code> for every 1 unit increase in <code>yrs.since.phd</code>.<a href="#fn7" class="footnoteRef" id="fnref7"><sup>7</sup></a> In other words, salary is predicted to increase by $985.30 for every additional year a professor has earned their Ph.D.</p>
<p>The <em>t</em>-statistic can be interpreted as <code>yrs.since.phd</code> explains the variability in <code>salary</code> 9.18 times more than <code>yrs.since.phd</code>’s inability to the explain the variability in <code>salary</code>.</p>
<p>The <em>p</em>-value of <code>yrs.since.phd</code> is identical to the <em>p</em>-value of the <code>(Intercept)</code> and has identical interpretations.</p>
<p>Now, if wanted, we can fill in our predicted model, <span class="math inline">\(\hat{Y} = b_0 + b_1X\)</span>, with the estimates from the coefficients table to predict (or estimate) other values of salary given a certain number of years since a professor has earned their Ph.D.</p>
<p><span class="math display">\[\hat{salary} = b_0 + b_1*yrs.since.phd = 91718.7+985.3*yrs.since.phd\]</span></p>
<p>For example, let’s say that we were interested in estimated the salary of professor’s who have worked for 2 years.</p>
<p><span class="math display">\[\hat{salary} = 91718.7+985.3*yrs.since.phd = 91718.7+985.3*2 = 93689.3\]</span></p>
</div>
</div>
<div id="statistical-decision" class="section level2">
<h2><span class="header-section-number">5.3</span> Statistical decision</h2>
<p>To determine if <code>yrs.since.phd</code> is statistically significant in predicting <code>salary</code>, we will compare its <em>p</em>-value with the alpha level (<span class="math inline">\(\alpha\)</span>) of <code>0.05</code>. <span class="math inline">\(\alpha\)</span> is the Type I error rate, or the probability that we are incorrectly rejecting the null hypothesis when it is actually true.</p>
<p>Given that the <em>p</em>-value of <code>&lt;2.2e-16</code> for the <code>yrs.since.phd</code> is less than the alpha level (<span class="math inline">\(\alpha\)</span>) of <code>0.05</code>, we will <code>reject</code> the null hypothesis.</p>
<p>We can also determine if the intercept is statistically significant. Given, that the <code>(Intercept)</code> had an identical <em>p</em>-value, we will also <code>reject</code> the null hypothesis.</p>
</div>
<div id="apa-statement" class="section level2">
<h2><span class="header-section-number">5.4</span> APA statement</h2>
<p>A regression was performed to test if the amount of years since obtaining a Ph.D. was related to their salary. The amount of years since obtaining a Ph.D. was significantly related to their salary, <em>b</em> = 985.3, <em>t</em>(395) = 9.18, <em>p</em> &lt; .001. For every passing year that a professor has earned their Ph.D., their salary is estimated to increase by $985.30.</p>
</div>
<div id="visualization" class="section level2">
<h2><span class="header-section-number">5.5</span> Visualization</h2>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(datasetSalaries, <span class="kw">aes</span>(yrs.since.phd, salary)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">alpha =</span> <span class="fl">0.25</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="dt">color =</span> <span class="st">&quot;#3182bd&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(
    <span class="dt">x =</span> <span class="st">&quot;Years since Ph.D.&quot;</span>,
    <span class="dt">y =</span> <span class="st">&quot;9-Month Salary (USD)&quot;</span>
  ) <span class="op">+</span>
<span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">labels =</span> dollar) <span class="op">+</span>
<span class="st">  </span><span class="kw">theme_classic</span>()</code></pre></div>
<div class="figure"><span id="fig:unnamed-chunk-18"></span>
<img src="practical-ext-of-intro-stats-in-psy-using-R_files/figure-html/unnamed-chunk-18-1.png" alt="A scatterplot of years since Ph.D. and salary along with the line of best fit. The gray band represents the 95% CI." width="672" />
<p class="caption">
Figure 5.1: A scatterplot of years since Ph.D. and salary along with the line of best fit. The gray band represents the 95% CI.
</p>
</div>

</div>
</div>
<div class="footnotes">
<hr />
<ol start="2">
<li id="fn2"><p><span class="math inline">\(\Sigma Contrast_{TenuredvAssistant}*Contrast_{AssociatevProfessor} = (2*0) + (1*-1) + (1*1) = 0\)</span><a href="simple-linear-regression.html#fnref2">↩</a></p></li>
<li id="fn3"><p><span class="math inline">\(\Sigma Contrast_{TenuredvAssistant}*Contrast_{AssociatevProfessor} = (2*0) + (1*-1) + (1*1) = 0\)</span><a href="simple-linear-regression.html#fnref3">↩</a></p></li>
<li id="fn4"><p><span class="math inline">\(\Sigma Contrast_{TenuredvAssistant}*Contrast_{AssociatevProfessor} = (2*0) + (1*-1) + (1*1) = 0\)</span><a href="simple-linear-regression.html#fnref4">↩</a></p></li>
<li id="fn5"><p><span class="math inline">\(\Sigma Contrast_{TenuredvAssistant}*Contrast_{AssociatevProfessor} = (2*0) + (1*-1) + (1*1) = 0\)</span><a href="simple-linear-regression.html#fnref5">↩</a></p></li>
<li id="fn6"><p><span class="math inline">\(\Sigma Contrast_{TenuredvAssistant}*Contrast_{AssociatevProfessor} = (2*0) + (1*-1) + (1*1) = 0\)</span><a href="simple-linear-regression.html#fnref6">↩</a></p></li>
<li id="fn7"><p><span class="math inline">\(\Sigma Contrast_{TenuredvAssistant}*Contrast_{AssociatevProfessor} = (2*0) + (1*-1) + (1*1) = 0\)</span><a href="simple-linear-regression.html#fnref7">↩</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="datasets.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="correlation.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
